title: Just do it
description: A place for an adventure
theme: just-the-docs

url: https://ducchinhpro123/just-do-it

aux_links:
  Template Repository: https://ducchinhpro123/just-do-it

callouts:
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: red
  important:
    title: Important
    color: purple
  tip:
    title: Tip
    color: green
